-- Seed data — run AFTER schema.sql
-- NOTE: Admin password hash is generated by scripts/seed.js
-- Run: node scripts/seed.js  (preferred — uses real bcrypt)
-- This file is provided as a reference only.

-- Default admin user
-- Password: Admin@1234  (change immediately after first login)
-- Hash below is for documentation; use scripts/seed.js for actual seeding
INSERT INTO users (name, email, password_hash, role) VALUES
('Admin', 'admin@fg.local', 'RUN_scripts/seed.js_TO_GENERATE', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Main category
INSERT INTO categories (name) VALUES ('Food & Grains') ON CONFLICT DO NOTHING;

-- Sub categories with shelf life per spec
INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Rice', 365 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Pulses', 540 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Wheat & Flour', 180 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Dry Fruits', 270 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Almonds', 270 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Spices & Seeds', 365 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;

INSERT INTO sub_categories (category_id, name, shelf_life_days)
SELECT c.id, 'Sugar & Jaggery', 730 FROM categories c WHERE c.name = 'Food & Grains'
ON CONFLICT DO NOTHING;
